name: Netlist, lists and schematics

on:
  push:
    branches: [ master, pulses_separ ]
  pull_request:
    branches: [ master, pulses_separ ]
  workflow_dispatch:


jobs:
  schematics:
    name: schematics exports
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: environement
        run: sudo apt-get install -y lepton-eda
      - name: setup build folders
        run: |
          mkdir arti
          mkdir arti/schematics
      - name: build
        run: |
          make DESTDIR=arti/schematics/ EXPORT_PROG=lepton-cli schemas 
      - name: return workflow as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pulsesgene_schematics
          path: arti

  lists:
    name: lists circuits
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: environement
        run: sudo apt-get install -y lepton-eda
      - name: setup build folders
        run: |
          mkdir arti
          mkdir arti/lists
      - name: build
        run: |
          make DESTDIR=arti/lists/ NETLIST_PROG=lepton-netlist lists
      - name: return workflow as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pulsesgene_lists
          path: arti

  pcb-net:
    name: netlist for PCB
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: environement
        run: sudo apt-get install -y lepton-eda
      - name: setup build folders
        run: |
          mkdir arti
          mkdir arti/PCB
      - name: build
        run: |
          make DESTDIR=arti/PCB/ NETLIST_PROG=lepton-netlist pcb
      - name: return workflow as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pulsesgene_PCB_net
          path: arti


  merge:
    runs-on: ubuntu-latest
    needs: [ schematics, lists, pcb-net ] 
    steps:
      - name: Merge artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          delete-merged: true
          name: pulses_gene_schema
