name: Spice and schemas

on:
  push:
    branches: [ master, pulses_separ ]
  pull_request:
    branches: [ master, pulses_separ ]

jobs:
  schemas:
    name: schemas exports
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: environement
        run: sudo apt-get install -y lepton-eda
      - name: setup build folders
        run: |
          mkdir arti
          mkdir arti/schemas
      - name: build
        run: |
          make DESTDIR=arti/schemas/ EXPORT_PROG=lepton-cli schemas 
      - name: return workflow as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pulsesgene_lists_schemas
          path: arti

  lists:
    name: lists circuits
    needs: schemas
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: environement
        run: sudo apt-get install -y lepton-eda
      - name: setup build folders
        run: |
          mkdir arti
          mkdir arti/lists
      - name: get workflow as artifacts
        uses: actions/download-artifact@v3
        with:
          name: pulsesgene_lists_schemas
          path: arti
      - name: build
        run: |
          make DESTDIR=arti/lists/ NETLIST_PROG=lepton-netlist lists
      - name: return workflow as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pulsesgene_lists_schemas
          path: arti

  pcb-net:
    name: netlist for PCB
    needs: lists
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: environement
        run: sudo apt-get install -y lepton-eda
      - name: setup build folders
        run: |
          mkdir arti
          mkdir arti/PCB
      - name: get workflow as artifacts
        uses: actions/download-artifact@v3
        with:
          name: pulsesgene_lists_schemas
          path: arti
      - name: build
        run: |
          make DESTDIR=arti/PCB/ NETLIST_PROG=lepton-netlist pcb
      - name: return workflow as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pulsesgene_lists_schemas
          path: arti


