name: Spice and schemas

on:
  push:
    branches: [ master, pulses_separ ]
  pull_request:
    branches: [ master, pulses_separ ]

jobs:


  spice:
    name: spice circuits
    needs: pcb-net
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: environement
        run: sudo apt-get install -y lepton-eda
      - name: setup build folders
        run: |
          mkdir arti
          mkdir arti/spice
      - name: get workflow as artifacts
        uses: actions/download-artifact@v3
        with:
          name: pulsesgene_build
          path: arti
      - name: build
        run: |
          make NETLIST_PROG=lepton-netlist BUILDDIR=arti/spice/ spice
      - name: return workflow as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pulsesgene_build
          path: arti

  simulation:
    name: simulation
    needs: spice
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: environement
        run: sudo apt-get install -y ghdl
      - name: setup build folders
        run: |
          mkdir arti
          mkdir arti/simulation
      - name: get workflow as artifacts
        uses: actions/download-artifact@v3
        with:
          name: pulsesgene_build
          path: arti
      - name: build
        run: |
          make BUILDDIR=arti/simulation/ simul
      - name: return workflow as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pulsesgene_build
          path: arti

  synth_ice40:
    name: synth_ice40
    needs: simulation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: environement
        run: sudo apt-get install -y ghdl yosys nextpnr-ice40
      - name: setup build folders
        run: |
          mkdir arti
          mkdir arti/synthesis
          mkdir arti/synthesis/ice40_lp384
      - name: get workflow as artifacts
        uses: actions/download-artifact@v3
        with:
          name: pulsesgene_build
          path: arti
      - name: build
        run: |
          make SYNTHDESTDIR=arti/synthesis/ice40_lp384 synth_ice40
      - name: return workflow as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pulsesgene_build
          path: arti

