name: Spice and schemas

on:
  push:
    branches: [ master, pulses_separ ]
  pull_request:
    branches: [ master, pulses_separ ]

jobs:


  spice:
    name: spice circuits
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: environement
        run: sudo apt-get install -y lepton-eda
      - name: setup build folders
        run: |
          mkdir arti
          mkdir arti/spice
      - name: build
        run: |
          make NETLIST_PROG=lepton-netlist BUILDDIR=arti/spice/ spice
      - name: return workflow as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pulsesgene_build
          path: arti

  simulation:
    name: simulation
    needs: spice
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: environement
        run: sudo apt-get install -y lepton-eda ghdl
      - name: setup build folders
        run: |
          mkdir arti
          mkdir arti/simulation
      - name: get workflow as artifacts
        uses: actions/download-artifact@v3
        with:
          name: pulsesgene_build
          path: arti
      - name: build
        run: |
          make NETLIST_PROG=lepton-netlist DESTDIR=arti/simulation/ simul
      - name: return workflow as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pulsesgene_build
          path: arti

  synth_ice40:
    name: synth_ice40
    needs: simulation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: environement
        run: |
          sudo apt-get install -y lepton-eda nextpnr-ice40 build-essential gcc bison flex gnat tcl-dev
          sudo apt-get install -y libreadline-dev gawk tcl-dev libffi-dev git graphviz xdot pkg-config python3 libboost-system-dev
          sudo apt-get install -y libboost-python-dev libboost-filesystem-dev zlib1g-dev
      - name: compile yosys
        run: |
          git clone https://github.com/YosysHQ/yosys
          cd yosys
          sudo make
          sudo make install 
      - name: compile ghdl
        run: |
          git clone https://github.com/ghdl/ghdl
          cd ghdl
          ./configure
          sudo make
          sudo make install
      - name: compile ghdl yosys plugin
        run: |
          git clone https://github.com/ghdl/ghdl-yosys-plugin
          cd ghdl-yosys-plugin
          sudo make install
      - name: setup build folders
        run: |
          mkdir arti
          mkdir arti/synthesis
          mkdir arti/synthesis/ice40_lp384
      - name: get workflow as artifacts
        uses: actions/download-artifact@v3
        with:
          name: pulsesgene_build
          path: arti
      - name: build
        run: |
          make NETLIST_PROG=lepton-netlist DESTDIR=arti/simulation/ SYNTHDESTDIR=arti/synthesis/ice40_lp384/ synth_ice40
      - name: return workflow as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pulsesgene_build
          path: arti

