name: Simulation and synthesis

on:
  push:
    branches: [ master, pulses_separ ]
  pull_request:
    branches: [ master, pulses_separ ]
  workflow_dispatch:


jobs:


  spice:
    name: spice circuits
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: environement
        run: sudo apt-get install -y lepton-eda
      - name: setup build folders
        run: |
          mkdir arti
          mkdir arti/spice
      - name: build
        run: |
          make NETLIST_PROG=lepton-netlist BUILDDIR=arti/spice/ spice
      - name: return workflow as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pulsesgene_spice
          path: arti

  simulation:
    name: simulation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: environement
        run: sudo apt-get install -y lepton-eda ghdl
      - name: setup build folders
        run: |
          mkdir arti
          mkdir arti/simulation
      - name: build
        run: |
          make NETLIST_PROG=lepton-netlist DESTDIR=arti/simulation/ simul
      - name: return workflow as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pulsesgene_simul
          path: arti

  synth_ice40:
    name: synth_ice40
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: environement
        run: |
          sudo apt-get install -y lepton-eda nextpnr-ice40 build-essential
          sudo apt-get install -y gcc bison flex gnat tcl-dev
          #sudo apt-get install -y libreadline-dev gawk libffi-dev git
          sudo apt-get install -y graphviz pkg-config
          sudo apt-get install -y python3 libboost-system-dev libboost-python-dev libboost-filesystem-dev zlib1g-dev
          sudo apt-get install -y berkeley-abc
      - name: compile yosys
        run: |
          git clone https://github.com/YosysHQ/yosys
          cd yosys
          sudo make
          sudo make install 
      - name: compile ghdl
        run: |
          git clone https://github.com/ghdl/ghdl
          cd ghdl
          ./configure
          sudo make
          sudo make install
      - name: compile ghdl yosys plugin
        run: |
          git clone https://github.com/ghdl/ghdl-yosys-plugin
          cd ghdl-yosys-plugin
          sudo make install
      - name: setup build folders
        run: |
          mkdir arti
          mkdir arti/synthesis
          mkdir arti/synthesis/ice40_lp384
      - name: build
        run: |
          make NETLIST_PROG=lepton-netlist DESTDIR=arti/simulation/ SYNTHDESTDIR=arti/synthesis/ice40_lp384/ synth_ice40
      - name: return workflow as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pulsesgene_synthesis
          path: arti



  merge:
    runs-on: ubuntu-latest
    needs: [ spice, simulation ] 
    steps:
      - name: Merge artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          delete-merged: true
          name: pulsesgene_simul_and_synth
