name: Spice and schemas

on:
  push:
    branches: [ master, pulses_separ ]
  pull_request:
    branches: [ master, pulses_separ ]

jobs:


  test_toolschain_ghdl_yosys_G_Y_plugin:
    name: test_toolschain_ghdl_yosys_G_Y_plugin
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: environement
        run: |
          sudo apt-get install -y lepton-eda nextpnr-ice40 build-essential gcc bison flex gnat tcl-dev
          sudo apt-get install -y libreadline-dev gawk tcl-dev libffi-dev git graphviz xdot pkg-config python3 libboost-system-dev
          sudo apt-get install -y libboost-python-dev libboost-filesystem-dev zlib1g-dev
      - name: compile yosys
        run: |
          git clone https://github.com/YosysHQ/yosys
          cd yosys
          sudo make
          sudo make install 
      - name: compile ghdl
        run: |
          git clone https://github.com/ghdl/ghdl
          cd ghdl
          ./configure
          sudo make
          sudo make install
      - name: compile ghdl yosys plugin
        run: |
          git clone https://github.com/ghdl/ghdl-yosys-plugin
          cd ghdl-yosys-plugin
          sudo make install
      - name: setup build folders
        run: |
          mkdir arti
          mkdir arti/synthesis
          mkdir arti/synthesis/ice40_lp384
      - name: build
        run: |
          make NETLIST_PROG=lepton-netlist DESTDIR=arti/synthesis/ SYNTHDESTDIR=arti/synthesis/ice40_lp384/ synth_ice40
      - name: return workflow as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test
          path: arti

